// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package empi

const (
	Version     = "v1.0.14"
	GitCommit   = "11f7850" // the commit JUST BEFORE the release
	VersionDate = "2022-08-24 23:40" // UTC
)

