// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package empi

const (
	Version     = "v1.0.4"
	GitCommit   = "573ee09" // the commit JUST BEFORE the release
	VersionDate = "2020-08-16 17:30" // UTC
)

