// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package empi

const (
	Version     = "v1.0.9"
	GitCommit   = "b160a03" // the commit JUST BEFORE the release
	VersionDate = "2020-11-22 11:49" // UTC
)

