ID = 'com.emer.empi.v2'
Name = 'empi'
Type = 'Library'
Version = 'v2.0.0-dev0.0.4'

[Generate]
  [Generate.Enumgen]
    AcceptLower = true
    LineComment = true

[Release]
  Package = 'empi'
  VersionFile = 'empi/version.go'

[Web]
  LoadingLabel = ''
  RandomVersion = false
